# 這是給FHIR執行的，要先在240 build好，上傳到docker hub，然後在這邊拉下來執行
version: '3.9'
services:
  app:
    image: 10.18.27.131:17180/fhir/ai-fhir-backend:v2.1.3
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      FHIR_SERVER_URL: http://10.69.12.83:8080/
      GRPC_SERVER_ADDRESS: 10.21.98.80:8001
      PYTHONUNBUFFERED: 1
      TZ: Asia/Taipei
    ports:
      - 8010:8000
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "7"
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - 8011:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  logger:
    image: 10.18.27.131:17180/aic/audit-logger:v1.0.0
    network_mode: "host"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    volumes:
      - ./logs:/var/log/minio-audit


